"""Declared field meanings. Never infer business semantics from inferred dtypes."""
TABLES = {
 'orders': ('olist_orders_dataset.csv', '每行一笔订单，状态为抽取时最终状态', ['order_id']),
 'items': ('olist_order_items_dataset.csv', '每行一个订单商品项，一笔订单可有多项', ['order_id','order_item_id']),
 'customers': ('olist_customers_dataset.csv', '每行一个订单使用的客户记录；不是独立自然客户', ['customer_id']),
 'products': ('olist_products_dataset.csv', '每行一个商品', ['product_id']),
 'sellers': ('olist_sellers_dataset.csv', '每行一个卖家；不是平台店铺访问日志', ['seller_id']),
 'payments': ('olist_order_payments_dataset.csv', '每行一笔订单的支付序号记录；一单可多次支付', ['order_id','payment_sequential']),
 'reviews': ('olist_order_reviews_dataset.csv', '每行一条评价记录；订单与 review_id 均不能先验当作唯一键', []),
 'geolocation': ('olist_geolocation_dataset.csv', '每行一个邮编前缀对应的地理记录；邮编不是唯一键', []),
 'translation': ('product_category_name_translation.csv', '每行一个葡语品类到英语名称的映射', ['product_category_name']),
}
# name: meaning, logical type / unit, expected domain / implementation note
FIELDS = {
 'order_id': ('订单标识', '字符串', '保留原始值；连接订单事实表'),
 'customer_id': ('订单使用的客户记录标识', '字符串', '连接 customers；不可直接用于跨订单复购'),
 'customer_unique_id': ('跨订单稳定客户标识', '字符串', '客户去重、RFM、新老客'),
 'order_status': ('抽取时订单状态', '枚举字符串', 'delivered/shipped/canceled/unavailable/invoiced/processing/created/approved'),
 'order_purchase_timestamp': ('订单创建时间', '日期时间，无时区', '按来源本地时间解释；不要擅自转换 UTC'),
 'order_approved_at': ('订单批准时间', '日期时间，无时区', '允许缺失，不等同精确到账流水时间'),
 'order_delivered_carrier_date': ('移交承运商时间', '日期时间，无时区', '允许缺失，需检查先后顺序'),
 'order_delivered_customer_date': ('送达客户时间', '日期时间，无时区', '缺失则无法判断交付时长和是否延迟'),
 'order_estimated_delivery_date': ('预计送达日期', '日期时间，无时区', '按日比较；预计当天送达不算延迟'),
 'order_item_id': ('订单内商品项序号', '正整数', '与 order_id 构成联合键；不是商品数量字段'),
 'product_id': ('商品标识', '字符串', '连接 products'),
 'seller_id': ('卖家标识', '字符串', '连接 sellers；同一订单可能涉及多个卖家'),
 'shipping_limit_date': ('卖家发货期限', '日期时间，无时区', '不是客户预计送达日期'),
 'price': ('商品项销售价格', '十进制金额 / BRL', '非负、最多两位小数；入库转整数分'),
 'freight_value': ('商品项分摊运费', '十进制金额 / BRL', '非负、最多两位小数；不计入本项目商品成交金额'),
 'customer_zip_code_prefix': ('客户邮编前五位', '五位字符串', '保留前导零；不要直接连接未聚合地理表'),
 'customer_city': ('客户所在城市', '文本', '命名可能不标准；一版优先州级汇总'),
 'customer_state': ('客户所在州代码', '两位字符串', '州级销售分析使用此字段'),
 'seller_zip_code_prefix': ('卖家邮编前五位', '五位字符串', '保留前导零'),
 'seller_city': ('卖家城市', '文本', '不是客户城市'),
 'seller_state': ('卖家州代码', '两位字符串', '卖家侧地区属性'),
 'product_category_name': ('葡语商品品类名称', '字符串', '可缺失；与翻译表映射可能不完整'),
 'product_category_name_english': ('英语品类名称', '字符串', '展示用；不替代原始品类键'),
 'product_name_lenght': ('商品名称长度，原列名拼写如此', '非负整数 / 字符数', '只有长度，没有商品名称正文'),
 'product_description_lenght': ('商品描述长度，原列名拼写如此', '非负整数 / 字符数', '只有长度，没有描述正文'),
 'product_photos_qty': ('商品图片数量', '非负整数 / 张', '不是销售数量'),
 'product_weight_g': ('商品重量', '非负数 / 克', '保留缺失与零的区别，零值需核查'),
 'product_length_cm': ('包装长', '非负数 / 厘米', '保留缺失；不是商品销量'),
 'product_height_cm': ('包装高', '非负数 / 厘米', '保留缺失'),
 'product_width_cm': ('包装宽', '非负数 / 厘米', '保留缺失'),
 'payment_sequential': ('订单内支付序号', '正整数', '与 order_id 构成联合键'),
 'payment_type': ('支付方式', '枚举字符串', 'credit_card/boleto/voucher/debit_card/not_defined'),
 'payment_installments': ('分期数', '非负整数 / 期', '可观测到 0；不要与支付记录条数混淆'),
 'payment_value': ('支付记录金额', '十进制金额 / BRL', '非负、两位小数；不直接当作商品成交金额'),
 'review_id': ('评价标识', '字符串', '须审计唯一性；可能跨订单重复'),
 'review_score': ('订单评分', '整数 / 星', '1–5；缺失不记为 0'),
 'review_comment_title': ('评价标题', '可空文本', '缺少标题不等于缺少评分；不输出原文'),
 'review_comment_message': ('评价正文', '可空文本', '可能包含自由文本信息；不纳入公开审计明细'),
 'review_creation_date': ('评价调查创建日期', '日期时间，无时区', '不同于回答时间'),
 'review_answer_timestamp': ('评价回答时间', '日期时间，无时区', '若取最近评价，以此排序并使用确定性并列规则'),
 'geolocation_zip_code_prefix': ('地理记录邮编前缀', '五位字符串', '非唯一，先聚合再用于维表连接'),
 'geolocation_lat': ('纬度', '数值 / 度', '有效范围 [-90,90]；合法坐标不等于业务合理'),
 'geolocation_lng': ('经度', '数值 / 度', '有效范围 [-180,180]；州级分析无需使用'),
 'geolocation_city': ('地理记录城市名', '文本', '同一邮编可能有多种拼写'),
 'geolocation_state': ('地理记录州代码', '两位字符串', '同一邮编可能关联多州，需要另行处理'),
}
